### ISSUE TITLE
Chinese translation of fundamentals is out of date

### ISSUE THREAD

**Issue by greggman** [gfxfundamentals/threejsfundamentals#101]
Compare the [English version](https://threejsfundamentals.org/threejs/lessons/threejs-fundamentals.html) to the [Chinese version](https://threejsfundamentals.org/threejs/lessons/zh_cn/threejs-fundamentals.html). Several diagrams were added after the translation happened.

**Comment by Gracidora** [comment]
Can I update the Chinese version?

**Comment by greggman** [comment]
Yes please
