### ISSUE TITLE
Brazilian Portuguese Translation - pt_BR

### ISSUE THREAD

**Issue by rafaelbuiu** [gfxfundamentals/threejsfundamentals#109]
Hey @greggman!

Thank you and the other collaborators for spending some time putting this together.

I've been working with Three.js for almost 4 years and and It is very hard to find resources in our language. So now is my turn to give back to the community and share what I've been translating it to Brazilian Portuguese.

I am already following the recommendations in the README.md but my question is:

_Should I finish the entire translation to start sending PRs or I can do it along the way?_

**Comment by greggman** [comment]
You can do it however you prefer.

**Comment by rafaelbuiu** [comment]
Great! Thanks..
