### ISSUE TITLE
Three.js Voxel(Minecraft Like) Geometry - Empty spots

### ISSUE THREAD

**Issue by ViniciusFXavier** [gfxfundamentals/threejsfundamentals#117]
In the text it says it has examples but they are not loaded

![image](https://user-images.githubusercontent.com/40774281/90417311-e2e4ac80-e089-11ea-9966-3d36a4575b7b.png)
URL: https://threejsfundamentals.org/threejs/lessons/threejs-voxel-geometry.html

**Comment by greggman** [comment]
Thank you for the bug report

Fixed

https://github.com/gfxfundamentals/threejsfundamentals/commit/b2845253dd116bfdadab479a79621232c36e92da
