### ISSUE TITLE
LUT to PNG converter generates empty black PNG file

### ISSUE THREAD

**Issue by eugene-ilyin** [gfxfundamentals/threejsfundamentals#129]
Hello

I have used tutorial by this link https://threejsfundamentals.org/threejs/lessons/threejs-post-processing-3dlut.html
In the end, there is an Adobe LUT to PNG converter.

When I'm applying .CUBE file I see a preview, but when I press "download" I receive an empty black PNG file.
Example of .CUBE file https://gofile.io/d/iJz2Yo

This PR fixes that problem.
https://github.com/gfxfundamentals/threejsfundamentals/pull/128

**Comment by greggman** [comment]
21ca469
