### ISSUE TITLE
I want to make the contribution for the Chinese translation

### ISSUE THREAD

**Issue by Roy-Kid** [gfxfundamentals/threejsfundamentals#183]
Hi, I really like this tutorial, and I want to do some translation to Chinese. Although I am a novice for threejs, I can learn the tutorial and translate it simultaneously. It can impel me to learn it more carefully. So I want to ask who is in charge of Chinese translation; I can ask about the plan and ask for a review if I can join this meaningful job.

**Comment by greggman** [comment]
I think you can just jump in and start translating something. 

Maybe start a new issue like this one https://github.com/gfxfundamentals/threejsfundamentals/issues/174 example for chinese to coordinate who is working on what.

**Comment by Roy-Kid** [comment]
OK! I find #23 is talking about Chinese translation. I will turn to discuss this with him.
