### ISSUE TITLE
The Korean translation for custom buffer geometry is out of date

### ISSUE THREAD

**Issue by greggman** [gfxfundamentals/threejsfundamentals#187]
r125 got rid of `Geometry` so the "Custom Geometry" article is been deprecated and all the "Custom BufferGeometry" needs to be updated not to reference `Geometry` and the old article

See https://github.com/gfxfundamentals/threejsfundamentals/commit/eca713beaf6a5a083a117bcccf21862fa7e661d1 for the English changes

**Comment by Seemspyo** [comment]
send you a pr for `kr/threejs-custom-buffergeometry.md`.
Please see #192.
