### ISSUE TITLE
Online Shadertoy editor for threejs using TypeScript

### ISSUE THREAD

**Issue by gregdegruy** [gfxfundamentals/threejsfundamentals#206]
Is there an online live editor like the one found there that supports TypeScript?

https://threejsfundamentals.org/threejs/lessons/threejs-fundamentals.html

**Comment by greggman** [comment]
I'm not sure what you're asking.

https://codesandbox.io supports typescript

**Comment by gregdegruy** [comment]
Thanks you yes I was looking for something like this https://codesandbox.io/s/icy-tree-brnsm?file=/src/App.tsx
