### ISSUE TITLE
Confusion about clockwise order of vertices in custom geometry tutorial

### ISSUE THREAD

**Issue by ralfstx** [gfxfundamentals/threejsfundamentals#25]
The [tutorial on custom geometries](https://threejsfundamentals.org/threejs/lessons/threejs-custom-geometry.html) has been very helpful. Thanks a lot!

There's one detail I had to struggle with. The tutorial states:

> The order we specify the vertices is important. To be pointing toward the outside of the cube
> they must be specified in a clockwise direction when that triangle is facing the camera.

However, I realized that in contrast to this statement, faces become visible only when the camera-facing side is created in *counter-clockwise* order. I came across [this stackoverflow answer](https://stackoverflow.com/a/17640540/247159) that also states that the default is CCW. Actually, everything works as expected when connecting vertices in CCW direction.

I'm probably missing something, but maybe it would help to clarify the mechanics in the tutorial.

**Comment by greggman** [comment]
Thanks! You're right. Fixed

https://github.com/greggman/threejsfundamentals/commit/ec72af3ab9b2b8a1a9f91f9d5da02bee4add5dc1
