### ISSUE TITLE
loading .obj file page is broken

### ISSUE THREAD

**Issue by e-cloud** [gfxfundamentals/threejsfundamentals#31]
see https://threejsfundamentals.org/threejs/lessons/threejs-load-obj.html

the demo loads an invalid file url

**Comment by greggman** [comment]
thanks for pointing that out. For now I revered to r105. In r108 the OBJLoader2 only works with ES7 modules. It will be some non-trival amount of work to refact the entire site to ES7 modules

**Comment by greggman** [comment]
You need to clear your cache or open your dev tools and check "Disable Cache when devtools open" (chrome) or the equivilent in another browser

**Comment by greggman** [comment]
This should be fixed now, using r108
