### ISSUE TITLE
2 warnings about EXT_frag_depth & EXT_shader_texture_lod extension not supported

### ISSUE THREAD

**Issue by Mardonis** [gfxfundamentals/threejsfundamentals#45]
Hello Gregg,

Liking your tutorials. I'm having a couple of warnings on your first tutorial at the bottom with the three cubes spinning. If you click on the codepen option and bring it up and choose console it gives me no warnings using v112 or below say r110. But if I change the threejs link to a r113 the latest ['https://rawgit.com/mrdoob/three.js/r113/build/three.module.js']('https://rawgit.com/mrdoob/three.js/r113/build/three.module.js') it gives two warnings 

THREE.WebGLRenderer: EXT_frag_depth extension not supported.
THREE.WebGLRenderer: EXT_shader_texture_lod extension not supported.

I have already asked in THREE.js about the issue but they say it's probably my platform. The thing I do not understand about it is if I use r112 it's fine. I'm using Google Chrome Version 78.0.3904.70 (Official Build) (64-bit). My ticket there is ShaderMaterial: Extension fragDepth no longer working. #18576 if you would like to look at it. I understand about platforms not having an extension but from working v112 to not working inv113, it doesn't add up. Do you see anything?

Thanks
Mardonis

**Comment by greggman** [comment]
I know of no reason why you'd get the warnings on r113 and not on r112 but maybe the three.js people decided to print the warnings.

I upgraded the tutorials to r113. I see no warnings

They are just that though, warnings, not errors so they're trying to give you a hint that certain features of three.js might be slow or might not work. AFAIK none of the tutorials use any features affected by those warnings

**Comment by Mardonis** [comment]
ok thank you for replying.
