### ISSUE TITLE
[SUGGESTION] Custom font per language?

### ISSUE THREAD

**Issue by Seemspyo** [gfxfundamentals/threejsfundamentals#79]
Hi, I just send you a pull request of korean translations for your series.

I'm happy with the outcome mostly, means there is one thing that I'm not happy with.

It's a font(font-family, font style wateva). With current font it's slightly difficult to read korean translations(looks quite messy).

I can just use like `toc.html` or something to override entire font, but I believe it's a bad practice.

Did you have any plan for custom font supports per language? I think it would make this series prettier.

**Comment by greggman** [comment]
I can either add something to the build process or can use `:lang(kr)` in the css

Is wateva a standard front across all platforms? Windows/MacOS/Linux/iOS/Android?

Is it a google font or some online font?

**Comment by Seemspyo** [comment]
I heared wateva stands for whatever. Guess native speakers doesn't really use that. Sorry.

Either cdn from fonts.google.com or locally uploaded fonts would be great. Google has some nice korean fonts and also I personally have some fonts file(.ttf, .woff) with free web liscence.

**Comment by greggman** [comment]
okay, you can set the fonts in `threejs/lessons/kr/lang.css`

The file should look something small like

```
/* Only comment in overrides as absolutely necessary! */
:root {
  --article-font-family: "best font for korean article text";
  --headline-font-family: "best font for korean headlines";
  /* a block of code */
  /* --code-block-font-family: "Lucida Console", Monaco, monospace; */
  /* a word in a sentence */
  /* --code-font-family: monospace; */
}
```

and of course references to the fonts, Google CDN sounds good but I know plenty of developers block google since they think they are being spied on.

notice the example above only overrides the article text and headlines. I'd prefer not to override code blocks unless absolutely necessary.

**Comment by Seemspyo** [comment]
Good! But I had to spend some minutes to find out some prerequisites.

1. fill up `baseDirname` prop to `langinfo.hanson`.

2. update `@gfxfundamentals/lesson-builder` dependency.

After that, this work like charm.

I think we should keep this issue open until `README.md` get updated, for those who might confused like me.

**Comment by greggman** [comment]
You shouldn't have needed the `baseDirname` but yes, sorry I forgot to tell you to type `npm install` to get the latest lesson-builder
