### ISSUE TITLE
A misinfo in "threejs-prerequisites"

### ISSUE THREAD

**Issue by Seemspyo** [gfxfundamentals/threejsfundamentals#87]
I had mentioned this misinfo in my korean translation as translator commentary only, since I thought someone might corrects this(which is not) in commentary.

But I think it's better original article to be fixed since this article(prerequisites) is specially for Javascript beginners.

The misinfo is about arrow function(lamda). As [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) says, the arrow function is

> a syntactically compact alternative to a regular function expression, although without its own bindings to the this, arguments, super, or new.target keywords.

In the article though, you said "arrow functions bind this". In some level of course, arrow functions can be made with `this` binding. But as a ECMA specification, it's more likely to not binding `this` but use `this` of parent execution context.

If you think I'm wrong or some misunderstanding is here. Please let me know.

**Comment by greggman** [comment]
That means the same thing.

    `foo = bar.bind(this);`

that `this` is the parent context. There is no non-parent context in the case of bind. bind is generating a new function. The code that calls `bind` is the parent. The `this` when bound is called is the parent context.

**Comment by Seemspyo** [comment]
It's a syntactic sugar of course, and basically those two are identical.

But those who are not familiar with javascript or ES2015 syntax might be confused about

> arrow functions bind this.

Since most of article about the arrow function says "arrow function gets it's `this` from parent context" or "there are no binding of `this`". Further, this article is for ES2015 newbie.

I might just overconcerned though, I think it's better to be obvious since javascript `this` is quiet complicated.

I know you don't likes to argue about such a small issue. I love your series, and as here myself a beginner of 3D world, your articles are really helpful. So if you think it's not a big deal, it's fine for me.
