### ISSUE TITLE
Can I translate Fundamentals part of ja?

### ISSUE THREAD

**Issue by tasotasoso** [gfxfundamentals/threejsfundamentals#96]
Hi, I want to translate "Fundamentals" part of ja such as "Primitives".
I saw " Translations Welcome!" message.
I know others are  translating the "basic" parts of ja (Translate Japanese-001 #92).
If I'll collide, please tell me.

**Comment by greggman** [comment]
Please do! Maybe @naotaro0123 can say what article/s they are working on so you can work on a different one. Or just pick one.

**Comment by tasotasoso** [comment]
Thank you for your reply! 
For the moment, I'll try threejs-primitives.md if @naotaro0123 already work on.

**Comment by naotaro0123** [comment]
Hi, I'm translating the threejs-responsive chapter. 
I will make PR for each page so that translation work will not be suffered.

**Comment by greggman** [comment]
ところで、ここで日本語でやり取りしていいですよ。私の日本語能力はあまり良くないけれど、勉強になるから頑張ります。
英語も勿論オッケーです。

**Comment by tasotasoso** [comment]
Hi, @naotaro0123 , thank you for your great attention and consideration!
I'll be careful with your PR and branch when I choose article.
